/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ObrasNovaRouteImport } from './routes/obras.nova'
import { Route as ObrasIdRouteImport } from './routes/obras.$id'
import { Route as DashboardGeralRouteImport } from './routes/dashboard.geral'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ObrasNovaRoute = ObrasNovaRouteImport.update({
  id: '/obras/nova',
  path: '/obras/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIdRoute = ObrasIdRouteImport.update({
  id: '/obras/$id',
  path: '/obras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGeralRoute = DashboardGeralRouteImport.update({
  id: '/geral',
  path: '/geral',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checklist': typeof ChecklistRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/dashboard/geral': typeof DashboardGeralRoute
  '/obras/$id': typeof ObrasIdRoute
  '/obras/nova': typeof ObrasNovaRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checklist': typeof ChecklistRoute
  '/relatorios': typeof RelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/dashboard/geral': typeof DashboardGeralRoute
  '/obras/$id': typeof ObrasIdRoute
  '/obras/nova': typeof ObrasNovaRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checklist': typeof ChecklistRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/dashboard/geral': typeof DashboardGeralRoute
  '/obras/$id': typeof ObrasIdRoute
  '/obras/nova': typeof ObrasNovaRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checklist'
    | '/dashboard'
    | '/relatorios'
    | '/admin/usuarios'
    | '/dashboard/geral'
    | '/obras/$id'
    | '/obras/nova'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checklist'
    | '/relatorios'
    | '/admin/usuarios'
    | '/dashboard/geral'
    | '/obras/$id'
    | '/obras/nova'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/checklist'
    | '/dashboard'
    | '/relatorios'
    | '/admin/usuarios'
    | '/dashboard/geral'
    | '/obras/$id'
    | '/obras/nova'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChecklistRoute: typeof ChecklistRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  RelatoriosRoute: typeof RelatoriosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  ObrasIdRoute: typeof ObrasIdRoute
  ObrasNovaRoute: typeof ObrasNovaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/obras/nova': {
      id: '/obras/nova'
      path: '/obras/nova'
      fullPath: '/obras/nova'
      preLoaderRoute: typeof ObrasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/$id': {
      id: '/obras/$id'
      path: '/obras/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof ObrasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/geral': {
      id: '/dashboard/geral'
      path: '/geral'
      fullPath: '/dashboard/geral'
      preLoaderRoute: typeof DashboardGeralRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardGeralRoute: typeof DashboardGeralRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGeralRoute: DashboardGeralRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChecklistRoute: ChecklistRoute,
  DashboardRoute: DashboardRouteWithChildren,
  RelatoriosRoute: RelatoriosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  ObrasIdRoute: ObrasIdRoute,
  ObrasNovaRoute: ObrasNovaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
